name: Build C#

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
   
    - name: Restore dependencies
      run: dotnet restore ./TestApp/TestApp.csproj

    - name: Build project
      run: dotnet build --no-restore --configuration Release ./TestApp/TestApp.csproj
